### ISSUE TITLE
ioctl return -1 when running rust logo example using kdMode::Graphics 

### ISSUE THREAD

**Issue by Ziqi-Yang** [Roysten/rust-framebuffer#21]
When I run the `rust-logo` example, it failed with this error message:
```
❯ sudo cargo run --example rust-logo
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/rust-logo`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FramebufferError { kind: IoctlFailed, details: "Ioctl returned -1: Inappropriate ioctl for device" }', examples/rust-logo/main.rs:18:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Source Line:
```
 18   │     let _ = Framebuffer::set_kd_mode(KdMode::Graphics).unwrap();
 ```
And backtrace:
```
❯ sudo RUST_BACKTRACE=1 cargo run --example rust-logo
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/rust-logo`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FramebufferError { kind: IoctlFailed, details: "Ioctl returned -1: Inappropriate ioctl for device" }', examples/rust-logo/main.rs:18:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: rust_logo::main
             at ./examples/rust-logo/main.rs:18:13
   5: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I knows only a little about fbdev and IDW why the problem occurs and how to fix it. Much appreciate if you could help :)

**Comment by Roysten** [comment]
This library does not work from a graphical user interface (X11/Wayland), you have to make sure to run the code from the linux framebuffer (e.g. ctrl-alt-f1 on Ubuntu).

If you did, then I will have to investigate this further.

**Comment by Ziqi-Yang** [comment]
Thank you for your advice! <3 
I didn't run the code from tty before. However, this time I tried to run code from tty, the same error occurs again. Here is the screen shot, which is produced by `fbgrab`.
![rust-framebuffer_error](https://github.com/Roysten/rust-framebuffer/assets/87977742/f921f7ef-838f-464e-a453-8fe72c4fcc1d)
Besides, there are some of my basic system information (IDW what to put here XD:
```
                   -`                    zarkli@myArch 
                  .o+`                   ------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.4.12-zen1-1-zen 
               `+oooooo:                 Shell: fish 3.6.1 
               -+oooooo+:                Resolution: 3200x2000 
             `/:-:++oooo+:               WM: sway 
            `/++++/+++++++:              Theme: Layan-Dark [GTK2/3] 
           `/++++++++++++++:             Icons: Tela-dracula [GTK2/3] 
          `/+++ooooooooooooo/`           Terminal: kitty 
         ./ooosssso++osssssso+`          CPU: 11th Gen Intel i7-11370H (8) @ 4.800GHz 
        .oossssso-````/ossssss+`         GPU: NVIDIA GeForce MX450 
       -osssssso.      :ssssssso.        GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
      :osssssss/        osssso+++.       Memory: 9926MiB / 15778MiB 
```

**Comment by Roysten** [comment]
I just verified this on my own Archlinux setup, and it seems that it is no longer allowed to access the framebuffer device as root. You can follow the steps in the [readme](https://github.com/Roysten/rust-framebuffer/blob/master/README.md) on how to add you to the `video` group. Once you have added yourself it will work and you no longer have to use sudo to run cargo or your executables :smile:.

I will remove the sudo part from the readme.

**Comment by Ziqi-Yang** [comment]
It works! Thanks you <3
